name: Dependant Jobs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "Job 1"

    steps:
      - name: Run Job 1
        run: echo "This is ${{ env.JOB_NAME }}"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    env:
      JOB_NAME: "Job 2"

    steps:
      - name: Run Job 2
        run: echo "This is ${{ env.JOB_NAME }}"

  job-3:
    runs-on: ubuntu-latest
    needs: job-2
    env:
      JOB_NAME: "Job 3"

    steps:
      - name: Run Job 3
        run: echo "This is ${{ env.JOB_NAME }}"
